global using System.IO.Abstractions;
global using System.Security.Cryptography;
global using System.Text;
global using System.Text.Json;
global using System.Text.Json.Serialization;
global using Aspirate.Secrets.Providers.Base64;
global using Aspirate.Secrets.Providers.Password;
global using Aspirate.Secrets.Services;
global using Microsoft.Extensions.DependencyInjection;
