global using System.Diagnostics.CodeAnalysis;
global using System.IO.Abstractions;
global using System.Text.Json;
global using Aspirate.Services.Interfaces;
global using Aspirate.Shared.Extensions;
global using Aspirate.Shared.Literals;
global using Aspirate.Shared.Models.AspireManifests;
global using Aspirate.Shared.Models.MsBuild;
global using HandlebarsDotNet;
global using Spectre.Console;
global using AspireProject = Aspirate.Shared.Models.AspireManifests.Components.V0.Project;
