name: Test dev container
on:
  workflow_dispatch:
  pull_request:
    paths:
      - "ext/devcontainer/**"
      - ".github/workflows/devcontainer-test.yaml"
    branches: [main]
  workflow_call:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        baseImage:
          [
            "mcr.microsoft.com/devcontainers/dotnet",
          ]
    steps:
      - uses: actions/checkout@v3

      - name: "Install latest devcontainer CLI"
        run: npm install -g @devcontainers/cli

      - name: "Generating tests for 'aspirate' against '${{ matrix.baseImage }}'"
        run: devcontainer features test -f aspirate -i ${{ matrix.baseImage }} .
        working-directory: ./ext/devcontainer

  test-scenarios:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: "Install latest devcontainer CLI"
        run: npm install -g @devcontainers/cli

      - name: "Testing 'aspirate' scenarios"
        run: devcontainer features test -f aspirate --skip-autogenerated .
        working-directory: ./ext/devcontainer

  test-global:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: "Install latest devcontainer CLI"
        run: npm install -g @devcontainers/cli

      - name: "Testing global scenarios"
        run: devcontainer features test --global-scenarios-only .
        working-directory: ./ext/devcontainer