name: Pull Requests

env:
  DOTNET_NOLOGO: true
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  CAKE_SETTINGS_SKIPVERIFICATION: true

on:
  - pull_request

jobs:
  build-test-pull-request:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Build and Test
        run: |
          dotnet tool restore
          dotnet cake
